-- Independent Scalp health snapshots. This table is observability-only and
-- does not share rows with simulated_trades, decisions, or Day Trading state.
CREATE TABLE IF NOT EXISTS public.scalp_health_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    status TEXT NOT NULL,
    state TEXT NOT NULL,
    reason TEXT NOT NULL DEFAULT '',
    last_trigger_at TIMESTAMPTZ NULL,
    age_seconds DOUBLE PRECISION NULL,
    cycles INTEGER NOT NULL DEFAULT 0,
    errors INTEGER NOT NULL DEFAULT 0,
    candidates INTEGER NOT NULL DEFAULT 0,
    approved INTEGER NOT NULL DEFAULT 0,
    rejected INTEGER NOT NULL DEFAULT 0,
    entries INTEGER NOT NULL DEFAULT 0,
    open_trades INTEGER NOT NULL DEFAULT 0,
    closed_trades INTEGER NOT NULL DEFAULT 0,
    wins INTEGER NOT NULL DEFAULT 0,
    losses INTEGER NOT NULL DEFAULT 0,
    gross_pnl_pct DOUBLE PRECISION NOT NULL DEFAULT 0,
    net_pnl_pct DOUBLE PRECISION NOT NULL DEFAULT 0,
    hold_evaluations INTEGER NOT NULL DEFAULT 0,
    exit_counts JSONB NOT NULL DEFAULT '{}'::jsonb,
    rejection_reasons JSONB NOT NULL DEFAULT '{}'::jsonb,
    entry_block_reasons JSONB NOT NULL DEFAULT '{}'::jsonb,
    last_decision JSONB NULL,
    details JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS idx_scalp_health_snapshots_created_at
    ON public.scalp_health_snapshots (created_at DESC);

ALTER TABLE public.scalp_health_snapshots ENABLE ROW LEVEL SECURITY;

-- Backend-only access: no anon/authenticated policy is created. The backend
-- connection uses the protected database role and remains able to write/read.
REVOKE ALL ON TABLE public.scalp_health_snapshots FROM anon, authenticated;
GRANT ALL ON TABLE public.scalp_health_snapshots TO postgres;
GRANT USAGE, SELECT ON SEQUENCE public.scalp_health_snapshots_id_seq TO postgres;
